### ISSUE TITLE
包 notify 相关问题

### ISSUE THREAD

**Issue by acha666** [seishinkouki/next_oshwhub_autosignin#2]
https://github.com/seishinkouki/next_oshwhub_autosignin/blob/a90dc2d886775825d1e836951831b4da61d65c16/oshw.py#L3

如上所示，oshw.py中引入了notify包，这似乎不是一个常用的python库

根据我的理解，这似乎是所谓`青龙面板`所内置的一个通知模块，不能在正常的python环境中运行

请问您有意将对此脚本进行更改以适配通常的python环境吗，十分感谢

**Comment by seishinkouki** [comment]
https://github.com/whyour/qinglong/blob/develop/sample/notify.py 把青龙的通知模块一起下载下来就行了, 青龙的通知很全了, 没必要重复造轮子
